---
- name: Regex replace to pull name of the EE
  set_fact:
    ee_name: "{{ item.key | regex_replace('.*\/(.*)\/$','\\1') }}"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ '/tmp/' + ee_name }}"
    state: directory
    mode: '0755'

- set_fact:
    ee_python: "{{ item.value }}"
    ee_bindep: []
    ee_base_image: "{{ venv_migrate_default_ee_url }}"
    builder_dir: "{{ '/tmp/' + ee_name }}"
    ee_image_push: false

- name: Create EE
  include_role:
    name: redhat_cop.ee_utilities.ee_builder
