# User may add controller auth creds to this file and encrypt it using `ansible-vault`
---
controller_hostname: https://controller.node
controller_username: admin
controller_password: secret123
controller_validate_certs: false
...
